# Generated by Django 5.1.7 on 2026-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluto_pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pet',
            new_name='pluto_pets__rescuer_5b14aa_idx',
            old_name='pluto_pets__rescuer_4dfdbf_idx',
        ),
        migrations.RenameIndex(
            model_name='pet',
            new_name='pluto_pets__species_c47480_idx',
            old_name='pluto_pets__species_38332b_idx',
        ),
        migrations.RenameIndex(
            model_name='petimage',
            new_name='pluto_pets__pet_id_e43d38_idx',
            old_name='pluto_pets__pet_id_485ae0_idx',
        ),
    ]
