# Generated by Django 5.1.7 on 2026-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluto_pets', '0004_merge_20260422_1621'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adoptionrequest',
            new_name='pluto_pets__pet_id_2ea743_idx',
            old_name='pluto_pets__pet_id_a5c8b4_idx',
        ),
        migrations.RenameIndex(
            model_name='adoptionrequest',
            new_name='pluto_pets__adopter_a402ea_idx',
            old_name='pluto_pets__adopter_15765c_idx',
        ),
        migrations.RenameIndex(
            model_name='petconversation',
            new_name='pluto_pets__pet_id_372673_idx',
            old_name='pluto_pets__pet_id_9c0714_idx',
        ),
        migrations.RenameIndex(
            model_name='petinterest',
            new_name='pluto_pets__pet_id_b429a5_idx',
            old_name='pluto_pets__pet_id_5878bb_idx',
        ),
        migrations.RenameIndex(
            model_name='petmessage',
            new_name='pluto_pets__convers_b026da_idx',
            old_name='pluto_pets__convers_72d78b_idx',
        ),
    ]
