# Generated by Django 5.1.7 on 2026-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluto_adopters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adopterreview',
            new_name='pluto_adopt_adopter_9e0ece_idx',
            old_name='pluto_adopt_adopter_f1f186_idx',
        ),
    ]
