# Generated by Django 5.1.7 on 2026-04-22 08:43

import auth.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('PET_LISTING_MANAGEMENT', 'Pet Listing Management'), ('USER_MANAGEMENT', 'User Management'), ('ADOPTION_MANAGEMENT', 'Adoption Management')], max_length=50, unique=True, verbose_name='Module')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADOPTER', 'Adopter'), ('RESCUER', 'Rescuer'), ('ADMIN', 'Admin')], default='ADOPTER', max_length=16, verbose_name='User Role')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='Optional for now, but required if email-based login is used.', max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be between 6 and 15 digits and may start with '+'.", regex='^\\+?1?\\d{6,15}$')], verbose_name='Phone Number')),
                ('avatar', models.URLField(blank=True, verbose_name='Avatar URL')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Location')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=16, verbose_name='User Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('direct_permissions', models.JSONField(blank=True, default=list, verbose_name='Direct Permissions')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
            ],
            options={
                'verbose_name': 'Admin Invitation',
                'verbose_name_plural': 'Admin Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admins', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_type', models.CharField(blank=True, max_length=100, verbose_name='Home Type')),
                ('pet_experience', models.TextField(blank=True, verbose_name='Pet Experience')),
                ('preferred_pet_type', models.CharField(blank=True, max_length=100, verbose_name='Preferred Pet Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adopter Profile',
                'verbose_name_plural': 'Adopter Profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='Allowed Actions')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='pluto_auth.adminprofile')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to='pluto_auth.permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Admin Permission',
                'verbose_name_plural': 'Admin Permissions',
            },
        ),
        migrations.CreateModel(
            name='RescuerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=150, verbose_name='Organization Name')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience Years')),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=16, verbose_name='Verification Status')),
                ('successful_adoptions', models.PositiveIntegerField(default=0, verbose_name='Successful Adoptions')),
                ('response_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stored as a percentage between 0 and 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Response Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rescuer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rescuer Profile',
                'verbose_name_plural': 'Rescuer Profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='user_requires_email_or_phone'),
        ),
        migrations.AddIndex(
            model_name='admininvitation',
            index=models.Index(fields=['email', 'expires_at'], name='pluto_auth__email_a986a7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['admin_profile', 'permission'], name='pluto_auth__admin_p_af7874_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminpermission',
            constraint=models.UniqueConstraint(fields=('admin_profile', 'permission'), name='unique_admin_permission'),
        ),
    ]
