# Generated by Django 5.1.7 on 2026-04-29 13:34

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pluto_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_requires_email_or_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.URLField(blank=True, verbose_name='Cover URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, validators=[auth.models.validate_bio_word_limit], verbose_name='Bio'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('username__isnull', False), ('phone__isnull', False), _connector='OR'), name='user_requires_email_username_or_phone'),
        ),
    ]
